### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by labourer-Lucas** [ilovexjp/jkb-simulator#2]
I wonder if you could improve this project by adding a scanning QR code function. This would help a lot when entering places need to scan venue code. Thanks a lot.

**Comment by ilovexjp** [comment]
Check out the new release and see if the new page meets your needs. Click the QR code button on the top right corner to switch between modes. Let us know whether or not that works for you.

**Comment by labourer-Lucas** [comment]
Thanks a lot.
