### ISSUE TITLE
在 iOS 14 的 Safari 上图片更换无法正常运行，但是 iOS 14 的 Chrome 支持。

### ISSUE THREAD

**Issue by manner18cm** [ilovexjp/jkb-simulator#4]

**Comment by shshiheng** [comment]
遇到了同样的问题，突破压缩到几十k了依然不行

**Comment by shenchao0120** [comment]
同样现象，照片大小调到20k也不太行，跪求大佬看看

**Comment by ilovexjp** [comment]
> 同样现象，照片大小调到20k也不太行，跪求大佬看看

原因可能是一处代码顺序的问题，Web Demo 已经更新，可以先试下还会不会出现这个问题；但目前加载较大文件时还是会出现问题，建议尽量在使用图片的时候都压缩一下。
