### ISSUE TITLE
请教一下如何在手机上使用？设备为iphone12

### ISSUE THREAD

**Issue by Nemobkbmydb** [ilovexjp/jkb-simulator#7]

**Comment by Nemobkbmydb** [comment]
safari无法打开网页
Cloudflare: [ilovexjp.pages.dev](https://ilovexjp.pages.dev/)

Netlify: [ilovexjp.netlify.app](https://ilovexjp.netlify.app/)

**Comment by Nemobkbmydb** [comment]
已解决

**Comment by Frankeke2077** [comment]
请问是怎么解决的呢？

**Comment by Nemobkbmydb** [comment]
两个方法，推荐2:
1、VPN梯子，但项目中的链接不稳定；
2、自己购买一个云服务商（如tx、阿里等），下载项目中的压缩文件，并部署到服务商上，通过公网IP访问，可参考：
https://blog.csdn.net/NicolasLearner/article/details/113355666?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-1-113355666-blog-122542363.pc_relevant_recovery_v2&spm=1001.2101.3001.4242.2&utm_relevant_index=4


https://blog.csdn.net/yzzz66/article/details/123708849


或搜索【宝塔 windows】 / 【宝塔 服务商】 / 【宝塔 网站搭建】


祝好！




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月8日 23:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
State ***@***.***> |
| 主题 | Re: [ilovexjp/jkb-simulator] 请教一下如何在手机上使用？设备为iphone12 (Issue #7) |

请问是怎么解决的呢？
