### ISSUE TITLE
ios 添加到主屏幕刘海处留白了

### ISSUE THREAD

**Issue by Shibuya-ku** [ilovexjp/jkb-simulator#8]

**Comment by aftercurve** [comment]
我也是

**Comment by xuri111111** [comment]
+1

**Comment by OwenZzzz** [comment]
![4c16f736878f13723dc9d1091edf2f9](https://user-images.githubusercontent.com/34888220/200214027-5950af73-ed9b-487f-a43a-2f358b852039.jpg)

同样问题

**Comment by ilovexjp** [comment]
如果是在“北京健康宝”页面安装的，可以试下在目录页安装。参考 https://github.com/ilovexjp/ykm-simulator/issues/20

**Comment by OwenZzzz** [comment]
> 如果是在“北京健康宝”页面安装的，可以试下在目录页安装。参考 [ilovexjp/ykm-simulator#20](https://github.com/ilovexjp/ykm-simulator/issues/20)

已验证目录页安装可以解决此问题。大佬厉害👍
